### DISCUSSION TITLE
интент с динамической частью

### DISCUSSION THREAD

**Discussion by ajamkin** [dext0r/ha-yandex-station-intents#52] [General]
Здравствуйте.
Спасибо за компонент!

Хотел узнать есть-ли какая-нибудь возможность создавать интенты с динамической частью?

идея в том что есть телевизор (в моем случае LG с webOS) и хочется облегчить ввод текста при помощи Алисы.
Отправка текста с HA на телевизор вроде не сложна, но вот только не понятно возможно-ли такое вообще сделать через умную колонку с Алисой.

Например что-то типа такого:

```
yandex_station_intents:
  intents:
    "Набери текст на телевизоре {input}": Ок 
```

```
automation:
  - alias: Набери текст на телевизоре
    trigger:
      - platform: event
        event_type: yandex_intent
        event_data:
          text: "Набери текст на телевизоре {input}"
    action:
      - service: webostv.command
        target:
          entity_id: media_player.lg_webos_tv
        data:
          command: InsertText
          payload: {{ trigger.event.data.input }}
```
тогда по идее, если на телевизоре открыта клавиатура, в текущий инпут должен вбиться текст.

Спасибо!
