### ISSUE TITLE
Просьба прояснить функционал

### ISSUE THREAD

**Issue by booroondookZ** [dext0r/ha-yandex-station-intents#11]
Пример из документации (урезан для удобства):
```
yandex_station_intents:
  intents:
    Кто нибудь дома: Сейчас проверю 
    Не выключай свет в прихожей: 
      say_phrase: Договорились
```

В первом примере текст голосового отклика указан сразу после команды, а во втором примере - через параметр "say_phrase".
Какая функциональная разница между этими способами, и какой из них когда рациональнее применять?

И еще один вопрос: можно ли (и как) задать для голосового отклика случайный выбор текста из нескольких вариантов.
Например, я хочу, чтобы на команду "Не выключай свет в прихожей" Алиса отвечала случайно выбранной фразой из вариантов "Договорились", "Окей, хозяин" и "Хорошо, так и быть".

**Comment by dext0r** [comment]
> В первом примере текст голосового отклика указан сразу после команды, а во втором примере - через параметр "say_phrase".
> Какая функциональная разница между этими способами, и какой из них когда рациональнее применять?

Это разные способы сделать одно и тоже. Необходимость в say_phrase появилась после возможности задавать синонимы. А первый способ - это сокращённая запись, когда нет необходимости в синонимах.

> И еще один вопрос: можно ли (и как) задать для голосового отклика случайный выбор текста из нескольких вариантов.

Компонент так не может, потому что ответ вшивается в сценарий УДЯ. Но можно отвечать рандомными фразами в автоматизации, например:

```yaml
automation:
  - id: good_night
    alias: Good Night
    trigger:
      - platform: event
        event_type: yandex_intent
        event_data:
          text: Спокойной ночи
    action:
      - service: media_player.play_media
        entity_id: '{{ trigger.event.data.entity_id }}'
        data:
          media_content_type: dialog  # или text
          media_content_id: >
            {{ ['Спокойной ночи!', 'Сладких снов!', 'Приятных снов!', 'Доброй ночи!']|random }}
```
