### ISSUE TITLE
Настройка фильтра в Yandex Smart Home

### ISSUE THREAD

**Issue by anklav24** [dext0r/ha-yandex-station-intents#12]
```
Режим device (условно-устаревший):

Требует установленный компонент Yandex Smart Home, в фильтрах необходимо разрешить media_player.yandex_station_intents
```

Поясните, пожалуйста, как провернуть?

Пробовал вот так
```
yandex_smart_home:
  filter:
    include_entities:
      - media_player.yandex_station_intents
```

```
Yandex.Station Intents
Служебный плеер Yandex Station Intents не найден в УДЯ. Убедитесь, что он разрешён в фильтрах в компоненте Yandex Smart Home, обновите список устройств в УДЯ и перезагрузите эту интеграцию.
```
