### ISSUE TITLE
Отработка команды в дополнение к произнесенной фразе

### ISSUE THREAD

**Issue by booroondook-eng** [dext0r/ha-yandex-station-intents#17]
На примере...
Допустим, в УДЯ есть объект типа "Освещение", имеющий имя "Свет на кухне".
В штатной конфигурации (т.е., без "яндекс-интентов") на команду "Алиса, выключи свет на кухне" будет просто выключен свет.
Но хотелось бы, чтобы на эту же команду Алиса не просто выключила свет, но еще и сказала что-нибудь - например, "Сейчас выключу".
Можно ли подобную задач решить с помощью "Яндекс-интентов"?
В принципе, я понимаю, что задачу можно решить "обходным путём" - то есть, не просто прописать ответную фразу, но еще создать автоматизацию, где триггером будет событие yandex_intent c текстом "Выключи свет на кухне", а последующим действием будет передача команды "Выключи свет на кухню" через вызов службы media_player.play_media с параметром media_content_type: command.
Но всё же хотелось бы более простого варианта - чтобы не городить дополнительную автоматизацию.

**Comment by booroondookZ** [comment]
> FYI Это неправильное название для светильника (https://wiki.yaboard.com/s/6u) 🙃
Несколько раз перечитал статью по вашей ссылке, но так и не понял, чем конкретно плох вариант "Свет на кухне".
> А чем не устраивает вот эта галка в приложении?
Тем, что нужно произнесение не стандартного или случайного текста, а конкретно того, который я хочу услышать.
Фраза "Сейчас выключу" была приведена мной чисто для примера.
> Скорее всего нет.
Я понимаю, что на текущий момент это не реализовано.
Но с другой стороны, в настоящий момент реализовано произнесение заданной фразы в ответ на произнесенную фразу.
Почему бы не дополнить этот функционал опцией передачи этого же самого текста в Алису в качестве команды?
А в конфигурации это могло бы выглядеть примерно так:
```
yandex_station_intents:
  intents:
    Выключи свет на кухне: Не боитесь остаться в темноте? Ну, ладно.
      options:
        send_as_command: true
```

**Comment by dext0r** [comment]
> Несколько раз перечитал статью по вашей ссылке, но так и не понял, чем конкретно плох вариант "Свет на кухне".

"Свет" - это служебное слово в УДЯ, включающее все светильники в комнате "кухне". Если у вас будет два светильника - то они оба попадут под эту команду.

> Почему бы не дополнить этот функционал опцией передачи этого же самого текста в Алису в качестве команды?

```
yandex_station_intents:
  intents:
    Выключи свет на кухне: Не боитесь остаться в темноте? Ну, ладно.
      options:
        send_as_command: true
```
Если в этом примере отправить команду "Выключи свет в кухне" в сторону колонки - мы получим бесконечный цикл из-за сработки интента.

> Тем не менее, возвращаясь теперь уже к моим баранам, замечу, что конфигурация может выглядеть и так:
```
yandex_station_intents:
  intents:
    Давайте попьем чаю: Отличная идея, сейчас включу свет на кухне.
      options:
        send_command: Включи свет на кухне.
```

А вот это вполне реализуемо, хоть и добавит дополнительную задержку по сравнению с "локальным" включением света через light.turn_on. Реализация этой функции сможет закрыть вашу потребность?

**Comment by booroondookZ** [comment]
`А вот это вполне реализуемо, хоть и добавит дополнительную задержку по сравнению с "локальным" включением света через light.turn_on. Реализация этой функции сможет закрыть вашу потребность?`
Вполне! И думаю, что не только мою. Спасибо!

**Comment by dext0r** [comment]
Начал тестировать реализацию и наткнулся на проблему: нельзя одновременно произносить текст и выполнять команду, так как станция пытается озвучить результат выполнения команды (от галки "выполнять команды умного дома без лишних слов" не зависит).
Есть плохой вариант: дождаться пока станция произнесёт нужный текст, а уже потом выполнить команду - но это очень долго и стабильно работать не будет.
Скорее всего задуманное вами адекватно не реализуемо :(

**Comment by dext0r** [comment]
Но этот функционал можно использовать для создания хитрых синонимов команд, например:
```
yandex_station_intents:
  intents:
    Сделай сильно теплее:
      execute_command: 'Сделай кондиционер теплее на 1 градус в {{ event.room }}'
```

Тем самым текст реально выполненной команды будет зависеть от комнаты, в которой находится колонка, которая её услышала.
