### ISSUE TITLE
Фразы с шаблонами

### ISSUE THREAD

**Issue by kaizer666** [dext0r/ha-yandex-station-intents#24]
Есть ли возможность задавать фразы с шаблонами? К примеру "Громкость на телеке 20", а вместо 20 указать переменную какую-нибудь, и её передавать уже в автоматизацию, к примеру

**Comment by c1tru55** [comment]
@dext0r а нельзя сделать так, чтобы фраза описывалась в конфиге с шаблоном, под капотом на каждую комбинацию создавался бы сценарий в УДЯ, но обрабатывались бы они через 1 евент с параметрами (из шаблона)?

**Comment by dext0r** [comment]
> @dext0r а нельзя сделать так, чтобы фраза описывалась в конфиге с шаблоном, под капотом на каждую комбинацию создавался бы сценарий в УДЯ, но обрабатывались бы они через 1 евент с параметрами (из шаблона)?

Не совсем понимаю, можно пример конфига?

**Comment by c1tru55** [comment]
> > @dext0r а нельзя сделать так, чтобы фраза описывалась в конфиге с шаблоном, под капотом на каждую комбинацию создавался бы сценарий в УДЯ, но обрабатывались бы они через 1 евент с параметрами (из шаблона)?
> 
> Не совсем понимаю, можно пример конфига?

ну что-то типа такого:
```
    Громкость на {{ volume }}:
      variables:
        volume: 
          type: range
          min: 0
          max: 20
    Открой {{ app }}:
      extra_phrases:
        - Включи {{ app }}
        - Запусти {{ app }}
      variables:
        app: 
          type: choice
          choices: 
            - ютуб
            - кинопоиск
            - плекс
```
