### ISSUE TITLE
Увеличение времени генерации TTS

### ISSUE THREAD

**Issue by DmitrySinitsa** [dext0r/ha-yandex-station-intents#31]
Каким-то образом после настройки Yandex.Station Intents сильно увеличивается время генерации TTS. Проблему обсуждал в https://t.me/c/1337651089/69157 по рекомендации удалил устройство, все компоненты (связанные с колонками) сносил и ставил заново, перенастраивал. В процессе этого тестирования HA перестал ловить события yandex_intent с тестируемой колонки. При этом вызов media_player.play_media на генерацию текста стал отрабатывать нормально (до этого было 4-6 сек). После перенастройки Yandex.Station Intents и Yandex Smart Home, события начали поступать в HA, но время генерации текста увеличилось до прежнего.

**Comment by dext0r** [comment]
Нужно включить дебаг для обоих компонентов, воспроизвести проблему и приложить сюда home-assistant.log

```
logger:
  default: warning
  logs:
    custom_components.yandex_station_intents: debug
    custom_components.yandex_station: debug
```
